"""init user table with correct columns

Revision ID: 3aa5f5a19999
Revises: 7b5cdbd5d858
Create Date: 2025-05-06 01:13:28.693553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aa5f5a19999'
down_revision = '7b5cdbd5d858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('user_pswd', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('user_fName', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('user_lName', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('user_token', sa.String(length=1000), nullable=True))
        batch_op.create_unique_constraint("uq_user_email", ['user_email'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_token')
        batch_op.drop_column('user_lName')
        batch_op.drop_column('user_fName')
        batch_op.drop_column('user_pswd')
        batch_op.drop_column('user_email')

    # ### end Alembic commands ###
