"""Add username to User and user info to PortfolioSummary

Revision ID: 69f43ccac127
Revises: 3aa5f5a19999
Create Date: 2025-05-06 11:46:33.213121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f43ccac127'
down_revision = '3aa5f5a19999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_username', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('user_email', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('creator_username', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('creator_email', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('shared_from_username', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('shared_from_email', sa.String(length=200), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('username')

    with op.batch_alter_table('portfolio_summary', schema=None) as batch_op:
        batch_op.drop_column('shared_from_email')
        batch_op.drop_column('shared_from_username')
        batch_op.drop_column('creator_email')
        batch_op.drop_column('creator_username')
        batch_op.drop_column('user_email')
        batch_op.drop_column('user_username')

    # ### end Alembic commands ###
