"""Add created_at to User model

Revision ID: 6a6dc7375693
Revises: 69f43ccac127
Create Date: 2025-05-11 17:24:55.656215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a6dc7375693'
down_revision = '69f43ccac127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), 
                                      server_default=sa.text('CURRENT_TIMESTAMP'), 
                                      nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
