"""Add strategy_description to Asset

Revision ID: 7b5cdbd5d858
Revises: cf15cdd4a27e
Create Date: 2025-05-05 08:25:02.044446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b5cdbd5d858'
down_revision = 'cf15cdd4a27e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strategy_description', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('strategy_description')

    # ### end Alembic commands ###
