"""Initial migration

Revision ID: cf15cdd4a27e
Revises: 
Create Date: 2025-05-05 07:21:33.102801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf15cdd4a27e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('asset_code', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('asset_code')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('portfolio_summary',
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('shared_from_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('input_updated_at', sa.DateTime(), nullable=True),
    sa.Column('metric_updated_at', sa.DateTime(), nullable=True),
    sa.Column('calculated_at', sa.Date(), nullable=True),
    sa.Column('allocation_json', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('initial_amount', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('return_percent', sa.Float(), nullable=True),
    sa.Column('cagr', sa.Float(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('is_editable', sa.Boolean(), nullable=True),
    sa.Column('is_shareable', sa.Boolean(), nullable=True),
    sa.Column('is_deletable', sa.Boolean(), nullable=True),
    sa.Column('is_shown', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['shared_from_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('portfolio_id')
    )
    op.create_table('prices',
    sa.Column('asset_code', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['asset_code'], ['assets.asset_code'], ),
    sa.PrimaryKeyConstraint('asset_code', 'date')
    )
    op.create_table('portfolio_change_log',
    sa.Column('portfolio_log_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('field_changed', sa.String(length=255), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_summary.portfolio_id'], ),
    sa.PrimaryKeyConstraint('portfolio_log_id')
    )
    op.create_table('portfolio_share_log',
    sa.Column('portfolio_share_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('from_portfolio_id', sa.Integer(), nullable=False),
    sa.Column('to_portfolio_id', sa.Integer(), nullable=False),
    sa.Column('shared_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_portfolio_id'], ['portfolio_summary.portfolio_id'], ),
    sa.ForeignKeyConstraint(['from_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['to_portfolio_id'], ['portfolio_summary.portfolio_id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('portfolio_share_id')
    )
    op.create_table('portfolio_version',
    sa.Column('portfolio_version_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('allocation_json', sa.Text(), nullable=False),
    sa.Column('portfolio_name', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('initial_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_summary.portfolio_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('portfolio_version_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_version')
    op.drop_table('portfolio_share_log')
    op.drop_table('portfolio_change_log')
    op.drop_table('prices')
    op.drop_table('portfolio_summary')
    op.drop_table('user')
    op.drop_table('assets')
    # ### end Alembic commands ###
